-- Create a new TYPE called grocery.
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);


-- Create a new TABLE called shopping_list that contains 6 columns and appropriate data types for each.
CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price decimal(12,2) NOT NULL,
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  checked BOOLEAN DEFAULT false NOT NULL,
  category grocery NOT NULL
);
